### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by hugobloem** [hugobloem/wyoming-microsoft-tts#40]

**Comment by nerijus** [comment]
Are docker images available somewhere?

**Comment by hugobloem** [comment]
Soon, I just need to set up building them for various platforms.

**Comment by hugobloem** [comment]
Hi, the Docker container is now avaible here: 
```bash
docker pull ghcr.io/hugobloem/wyoming-microsoft-tts-noha:latest
```

**Comment by nerijus** [comment]
Thank you. `uri` example in Readme should probably be `tcp://0.0.0.0:10200` instead of `tcp://0.0.0.0:10300`?

**Comment by nerijus** [comment]
I do not see the port open. I use podman, not docker, and run it like this:
```
podman run \
                          --name=wyoming-microsoft-tts \
                          --network=host \
                          -p 10200:10200 \
                          ghcr.io/hugobloem/wyoming-microsoft-tts-noha:latest --service-region northeurope --subscription-key b2d.... \
                          --uri tcp://192.168.1.10:10200 --voice lt-LT-OnaNeural --debug
```
(tried with `tcp://0.0.0.0:10200` too).
`ss -nlp|grep 10020` does not list an open port, `telnet 192.168.1.10 10020` gives Connection refused.
I have a Rhasspy container with similar setup (it has `-p 12101:12101`), and I do see 12101 port opened with `ss` and can telnet into it.

**Comment by nerijus** [comment]
Oops, I am dumb, used 10020 instead of 10200 :) The port is open.

**Comment by nerijus** [comment]
Thank you, I was able to add both tts and stt to HA and it works!
