### ISSUE TITLE
Add speakerProfileId as optional

### ISSUE THREAD

**Issue by loryanstrant** [hugobloem/wyoming-microsoft-tts#62]
Firstly, this is awesome - thank you!

Secondly, is there any chance you could include SpeakerId as an optional field to pass through?
For example, here is the SSML I need to pass through to Personal Voice in order for it to work:
```
<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='http://www.w3.org/2001/mstts' xml:lang='en-US'>
    <voice name='DragonLatestNeural'> 
    <mstts:ttsembedding speakerProfileId='your speaker profile ID here'> 
    I'm happy to hear that you find me amazing and that I have made your trip planning easier and more fun.  
    </mstts:ttsembedding> 
    </voice> 
</speak>
```

It would be awesome if the speakerProfileId could be added as an optional input.

**Comment by hugobloem** [comment]
Hi, thank you for your interest!

Unfortunately, I don't think this is something that [Wyoming](https://github.com/rhasspy/wyoming) supports at the moment. You could ask there if they are looking to add this functionality.

I hope this helps.
