### ISSUE TITLE
May I know the docker setting?

### ISSUE THREAD

**Issue by pabian84** [hugobloem/wyoming-microsoft-tts#65]
Service-region and subscription-key can be found by referring to the Azure site, but I am not sure what to do with the rest of the key values.
In particular, the voice is the same as the required value, but I don't know what kind of list there is.

Can I get some help?

**Comment by hugobloem** [comment]
Hi,

You can leave most of these settings on their default value as you can change the location and voice within Home Assistant on the fly. However, if you want to specify a default language and voice have a look in [`voices.json`](../blob/main/wyoming_microsoft_tts/voices.json) where all possible voices are listed. Then, use its ID to specify your preferred voice e.g. `af-ZA-WillemNeural`.

Hope this helps.
