### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by st3fannldev** [hugobloem/wyoming-microsoft-tts#81]
I use this in docker:
--service-region westeurope --subscription-key <redacted> --uri tcp://0.0.0.0:10200 --voice nl-NL-ColetteNeural

I am getting the following error, please help? :)

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.12/site-packages/wyoming/server.py:31> exception=AttributeError("'NoneType' object has no attribute 'name'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/wyoming_microsoft_tts/handler.py", line 67, in handle_event
    text=synthesize.text, voice=synthesize.voice.name
                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by hugobloem** [comment]
Hoi Stefan,

Sorry this is a bug, I will upload a new version soon.
